version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
  tests:
    build: .
    volumes:
      - .:/app
    command: pytest -v
    depends_on:
      - api